### PR TITLE
Optimise to omit frame pointer even in a debug build

### LINKED ISSUE #11: It's not possible to generate a debug build with nrf51-sdk 1.0.1
``` sh
$ yotta build -d
# snip
yotta_modules/nrf51-sdk/source/nordic_sdk/components/libraries/bootloader_dfu/bootloader_util.c: In function 'bootloader_util_reset':
yotta_modules/nrf51-sdk/source/nordic_sdk/components/libraries/bootloader_dfu/bootloader_util.c:126:1: error: r7 cannot be used in asm here
```

### PR DESCRIPTION
**Pull request by LiyouZhou**
In bootloader_util.c there is a piece of asm that uses
r7. r7 is usually used by gcc as a frame pointer hence gcc
would complain even though a frame pointer is not actually
needed. -fomit-frame-pointer prevents this warning.

fixes #11

@pan- @andresag01 please review

### CODE REVIEW

**Comment by andresag01** [comment]
This seems to fix the problem. I tried building with GCC and `-d` and it succeeds. Also the application works as expected.

Lets wait for @pan- to comment.

**Comment by pan-** [comment]
It's ok for me, I merge.
